# Generated by Django 4.2.3 on 2024-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Idmessage', models.AutoField(primary_key=True, serialize=False, verbose_name='Idmessage')),
                ('Emeteur', models.EmailField(max_length=254)),
                ('Recepteur', models.EmailField(max_length=254)),
                ('Text', models.TextField()),
                ('SendAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
                'db_table': ' Message',
            },
        ),
    ]
